# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 30
  reconnect: true
  host: <%= ENV['MYSQL_HOST'] %>
  database: <%= ENV['MYSQL_DATABASE']%>
  username: <%= ENV['MYSQL_USERNAME']%>
  password: <%= ENV['MYSQL_PASSWORD']%>
  connect_timeout: 3


development:
  <<: *default

test:
  <<: *default
  database: 'admintest'
