# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88ebe17be5a8ee78425d664f07468d667614ae857bf56141a7500c1a03fb9df65c6ece634cb49ef8751c699926359b95920a967d62c0e28d43b680f37db33b98

test:
  secret_key_base: 728dc8eb86c6b4006e491254857918b1b16268df42059593003944dc16adfdfb8ca5140295d25e0723ae858429664b37f43dc2e405e6d94d97e7f05aec135f5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
